### ISSUE TITLE
October 5 issues 

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/TFBS_presence#10]
For @joanne-chen 

Run the pipeline on all alignments with all motifs.

1. Run pipeline with threshold 95.
2. Run with output of all positions
- Run a test to see if all positions are actually being output before running on everything. If you don't see all the positions, let me know and I will track down my notes when I ran into this before.  Basically one of the functions for mapping TFBS in the biomotif package defaults to a certain threshold.

**Comment by joanne-chen** [comment]
Just to clarify- you only want the "filtered" table to be outputted for now when running the pipeline? Is that what you mean by all positions?
