### ISSUE TITLE
Code Review July 12

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/TFBS_presence#4]
### Positions

These are just notes on which tables are important and which are not. 

- `position_species_tables` - you can remove this code
-  `filtered_tables` - position of each TFBS per alignment file :fire: **very useful table**
  - [ ] This would be even more useful with the extracted motif at that position, from all species even if they do not have the motif (See Motifs below).
   -  [ ] This would be useful to find TFBS wobble and record how TFBS decay
-  `group_by_combos_tables` how many "groups" there are per alignment file :fire:  **very useful table**
-  `frequent_all_alignments` the frequency of groups across all alignments :fire: **very useful table**

### Code organizing

-  [x]  split the functions into their own python script (`Motif_Scoring_and_Extraction.py`)
-  [x]  delete the functions from the exploratory analysis (`Motif_Scoring_and_Extraction.ipynb`)
-  [x]  import the `Motif_Scoring_and_Extraction.py` into the `Motif_Scoring_and_Extraction.ipynb` and test to see if everything works. 
-  [x]  add more comments wherever if you think they would clarify anything.
 
### Motifs

 Give a stab at these tasks.

-  [x]  Read through the motifs function
-  [x]  understand how it works
-  [x]  try pulling out some motifs
-  [ ]  Overall goal to attach motifs to `filtered_tables`

**Comment by joanne-chen** [comment]
Some updates:
- The Jupyter notebook is now super clean and short. All the functions have been moved to MSE.py.
- I changed the .py file name to MSE.py for convenience, and added some more functions to it (just to make our lives easier as we run analysis).
- All we need to do in the Jupyter notebook now is run the pipeline function. That will go through essentially all the smaller functions

**Comment by iamciera** [comment]
The unfinished items were added to a new project.
