### ISSUE TITLE
Code Review and Assignments September 27

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/TFBS_presence#9]
## Overview

Please see the [worklflow](https://github.com/DiscoveryDNA/TFBS_presence/blob/master/img/TFBS-workflow-01.jpg). The best way to proceed is to split up the work according to the two groups (bottom and top) in the workflow. The bottom part starts from the output of the top part. I would love to make it to the end of this pipeline, whatever way possible,  then spend some time optimizing. I think the first part is almost complete, but would love to get Niharika started on the next part.  

### Joanne:

Thank you for splitting up the code.  I want to make sure this splitting makes sense. I would like for them to be split so that you could run the threshold settings functions by itself and the pipeline() functions by itself if needed (with no threshold).  Maybe it will help if I explain how I foresee the code being used.

In order to run `pipeline()`, someone first has to run `stand_cutoff(motif_path)`. This calculates the threshold and makes it set and can be used as an argument in 'pipeline()'. It looks like @joanne you started trying this out in [mapping_TFBS_10Sept2018.ipynb](https://github.com/DiscoveryDNA/TFBS_presence/blob/master/code/mapping_TFBS_10Sept2018.ipynb). One more point, if there is no percentage set, the threshold default should be zero. This will help so these tools can be used for the Neural Network team.

#### Breakdown of issues:

- [x] Finish last weeks items. Can you put any of the points that you need to finish below this comment in this issue.
- [x] Please read through the updated README.md.  Can you finish the documentation for thresholds? Also look through and see if you need to add anything that would be helpful or fix anything that seems wrong. 

### Niharika (@ndesaraju)

Since you are so biology focused I think it is important for you to start working with data immediately. I hope you have a general idea of how this program works. I think we should set a time next week so you and I can meet one on one.  We can go through the biology or code if you want , please look through below and give it a shot so you have questions ready.  

I have generated some test output files for you to start playing with. You will start writing the next steps. 

#### Breakdown of issues

- [x] Set up a time to meet one on one next week.
- [x] Take a look at workflow, try to understand what is being asked.

**For the Raw Motif Extraction Part**:
1. You start a notebook that takes the output of what @joanne-chen built and adding a column with the exact motif sequence (~6 letter nucleotide sequence) from the raw sequence files.  So there are two inputs.

1. The output examples are located in [data/output/bcd](https://github.com/DiscoveryDNA/TFBS_presence/tree/master/data/output/bcd) and the raw sequence files located at [/data/alignments](https://github.com/DiscoveryDNA/TFBS_presence/tree/master/data/alignments)  
2. The species column in the output files allows you to know which raw sequence file to read and which sequence within the raw sequence file you need to retrieve. 
3. You use the raw_position column in the output files to know where in the alignment sequence to retrieve the sequence and then add that sequence to a new column. 

The Align part is essentially the same but instead you use the alignment files.

Essentially the main thing you will need learn is how to use [Biopython](http://biopython.org/DIST/docs/tutorial/Tutorial.html) to extract sequences from .fasta files. Biopython is the main library that is used in Python to handle biological information. Sections that you will need to learn include: [simple fasta parsing](http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc11) and [chapter 3](http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc16).

**Comment by Niharika** [comment]
Hi,

I think you have the wrong alias

-Niharika

**Comment by iamciera** [comment]
Yes!  Thank @Niharika, all fixed.
